### ISSUE TITLE
Potential Virus!!

### ISSUE THREAD

**Issue by lucasbr15** [vaibhavard/Free-GPT4-GUI#1]
After downloading this executable, my webcam mysteriously started being used, possibly due to a virus. Please report this repository!

**Comment by vaibhavard** [comment]
Ok.

**Comment by lucasbr15** [comment]
![Screenshot_1](https://github.com/vaibhavard/Free-GPT4-GUI/assets/97372669/6764f58f-eb63-4875-897c-bd01e33ae9c2)

**Comment by vaibhavard** [comment]
I will be removing this github app immediately.
